#!/usr/bin/env node
'use strict';
const fs=require('fs'), path=require('path'), crypto=require('crypto');
function arg(name, def=null){ const i=process.argv.indexOf(name); return i>=0?process.argv[i+1]:def; }
const levelFile=arg('--level'); const outDir=path.resolve(arg('--out','oracle-fps-out'));
const beautySpp=Number(arg('--beauty-spp','32')); const irrSpp=Number(arg('--irr-spp','128'));
const xres=Number(arg('--xres','384')); const yres=Number(arg('--yres','216'));
const voxelOverride=Number(arg('--voxel-meters','0.1')); const cameraCount=Number(arg('--cameras','3'));
if(!levelFile) throw new Error('--level required'); fs.mkdirSync(outDir,{recursive:true});
function shaFile(p){return crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');}
function clamp(x,a=0,b=1){return Math.min(b,Math.max(a,x));}
function loadLevel(file){
 const m=require(path.resolve(file)); let L;
 if(m.generateIslandRavine) L=m.generateIslandRavine();
 else if(m.generateBunkersUnderCanopy) L=m.generateBunkersUnderCanopy({voxelSizeM:voxelOverride});
 else if(m.generateHoledBuildingAmongTrees) L=m.generateHoledBuildingAmongTrees({voxelMeters:voxelOverride,resolutionStrategy:'reference-resample'});
 else if(m.buildBuildingCarcassAmongTrees) L=m.buildBuildingCarcassAmongTrees({voxelMeters:voxelOverride,resolutionPolicy:'reference-resample'});
 else throw new Error('unsupported level module '+file);
 const vol=L.volume||null;
 const dims=L.dimensions?[L.dimensions.x,L.dimensions.y,L.dimensions.z]:vol?[vol.dimX,vol.dimY,vol.dimZ]:[L.sizeX,L.sizeY,L.sizeZ];
 const vm=L.voxelSizeMeters??L.voxelSizeM??L.profile?.voxelMeters??voxelOverride;
 const table=L.materials||L.materialTable||m.MATERIAL_TABLE;
 let get, dense=null;
 if(vol && typeof vol.toDense==='function') { dense=vol.toDense(); const [X,Y,Z]=dims; get=(x,y,z)=>(x<0||y<0||z<0||x>=X||y>=Y||z>=Z)?0:dense[x+X*(y+Y*z)]|0; }
 else if(vol && typeof vol.getVoxel==='function') get=(x,y,z)=>vol.getVoxel(x,y,z)|0;
 else if(L.voxels){ const [X,Y,Z]=dims, a=L.voxels; dense=a; get=(x,y,z)=>(x<0||y<0||z<0||x>=X||y>=Y||z>=Z)?0:a[x+X*(y+Y*z)]|0; }
 else throw new Error('no supported voxel storage');
 return {module:m,level:L,dims,vm,table,get,dense};
}
function familyColor(f,v){ const t=(v&31)/31; const palettes={1:[[.30,.31,.31],[.58,.56,.50]],2:[[.20,.12,.06],[.45,.30,.14]],3:[[.08,.26,.045],[.24,.52,.08]],4:[[.20,.075,.025],[.52,.32,.15]],5:[[.04,.19,.025],[.24,.48,.07]],6:[[.38,.07,.015],[.78,.33,.025]],7:[[.20,.22,.25],[.72,.68,.58]]}; const p=palettes[f]||[[.35,.35,.35],[.6,.6,.6]]; return p[0].map((a,i)=>a+(p[1][i]-a)*t); }
function matInfo(desc,id){ desc=desc||{}; const name=(desc.name||desc.description||desc.familyName||('mat'+id)).toLowerCase(); let base=desc.base||desc.baseRGB||desc.albedoHint||null; if(!base){const f=desc.family??(id>>5),v=desc.variant??(id&31); base=familyColor(f,v);} base=base.map(v=>clamp(Number(v)||0,0,.98)); const rough=clamp(desc.roughness??((desc.family===5||desc.family===6)?.62:.82),0,1); const metallic=clamp(desc.metallic??0,0,1); let emission=Array.isArray(desc.emission)?desc.emission.slice(0,3):[0,0,0]; if((desc.emissionStrength||0)>0 && desc.emissionColor) emission=desc.emissionColor.map(v=>v*desc.emissionStrength); const transparent=/water|glass/.test(name) || (desc.transmission??0)>.72; const kind=/water/.test(name)?'water':/glass/.test(name)?'glass':transparent?'dielectric':metallic>=.55?'conductor':'diffuse'; return {id,name,base,roughness:rough,alpha:rough*rough,metallic,emission,kind,eta:kind==='water'?1.333:1.5}; }
const W=loadLevel(levelFile), [X,Y,Z]=W.dims; const infos=Array.from({length:256},(_,i)=>matInfo(W.table?.[i],i));
function trans(id){return id!==0 && ['water','glass','dielectric'].includes(infos[id]?.kind);} function opaque(id){return id!==0&&!trans(id);} function emissive(id){return id!==0&&infos[id]?.emission?.some(v=>v>0);}
function sample(x,y,z){return (x<0||y<0||z<0||x>=X||y>=Y||z>=Z)?0:W.get(x,y,z);}
function boundary(a,b,stats){ if(a===b)return 0; if(a&&!b)return a; if(!a&&b)return -b; if(a&&b){const ta=trans(a),tb=trans(b); if(ta&&!tb)return -b; if(!ta&&tb)return a; if(ta&&tb&&a!==b){stats.ambiguousTransmissive++;return 0;}} return 0; }
const stats={rawBoundaryCells:0,greedyQuads:0,ambiguousTransmissive:0,byMaterial:{},byAxisSign:{}}; const quads=new Map(); function pushQuad(mat,q){if(!quads.has(mat))quads.set(mat,[]);quads.get(mat).push(q);stats.greedyQuads++;stats.byMaterial[mat]=(stats.byMaterial[mat]||0)+1;}
const dims=[X,Y,Z]; for(let d=0;d<3;d++){const u=(d+1)%3,v=(d+2)%3,U=dims[u],V=dims[v],mask=new Int16Array(U*V); for(let s=-1;s<dims[d];s++){let n=0;for(let j=0;j<V;j++)for(let i=0;i<U;i++){const a=[0,0,0],b=[0,0,0];a[d]=s;b[d]=s+1;a[u]=b[u]=i;a[v]=b[v]=j;const lab=boundary(sample(...a),sample(...b),stats);mask[n++]=lab;if(lab)stats.rawBoundaryCells++;} for(let j=0;j<V;j++)for(let i=0;i<U;){const idx=i+U*j,lab=mask[idx];if(!lab){i++;continue;}let w=1;while(i+w<U&&mask[idx+w]===lab)w++;let h=1;outer:for(;j+h<V;h++)for(let k=0;k<w;k++)if(mask[i+k+U*(j+h)]!==lab)break outer;for(let yy=0;yy<h;yy++)for(let xx=0;xx<w;xx++)mask[i+xx+U*(j+yy)]=0;const sign=lab>0?1:-1,mat=Math.abs(lab);pushQuad(mat,[d,sign,s+1,i,j,w,h]);const k=`${d}${sign>0?'+':'-'}`;stats.byAxisSign[k]=(stats.byAxisSign[k]||0)+1;i+=w;}}}
const shift=[-X*W.vm/2,0,-Z*W.vm/2]; function qverts(q){const [d,sign,plane,i,j,w,h]=q,u=(d+1)%3,v=(d+2)%3;const p=[0,0,0],du=[0,0,0],dv=[0,0,0];p[d]=plane;p[u]=i;p[v]=j;du[u]=w;dv[v]=h;const arr=[p,[p[0]+du[0],p[1]+du[1],p[2]+du[2]],[p[0]+du[0]+dv[0],p[1]+du[1]+dv[1],p[2]+du[2]+dv[2]],[p[0]+dv[0],p[1]+dv[1],p[2]+dv[2]]];return arr.map(a=>a.map((x,k)=>x*W.vm+shift[k]));}
function writePly(mat,qs){const nV=qs.length*4,nF=qs.length*2,name=`mesh_mat_${String(mat).padStart(3,'0')}.ply`,p=path.join(outDir,name);const header=Buffer.from(`ply\nformat binary_little_endian 1.0\ncomment generated by voxel_fps_oracle.js\nelement vertex ${nV}\nproperty float x\nproperty float y\nproperty float z\nelement face ${nF}\nproperty list uchar uint vertex_indices\nend_header\n`);const vb=Buffer.allocUnsafe(nV*12);let vo=0;for(const q of qs)for(const v of qverts(q))for(const x of v){vb.writeFloatLE(x,vo);vo+=4;}const fb=Buffer.allocUnsafe(nF*13);let fo=0,base=0;for(const q of qs){const sign=q[1],tris=sign>0?[[0,1,2],[0,2,3]]:[[0,3,2],[0,2,1]];for(const t of tris){fb.writeUInt8(3,fo++);for(const k of t){fb.writeUInt32LE(base+k,fo);fo+=4;}}base+=4;}fs.writeFileSync(p,Buffer.concat([header,vb,fb]));return{name,sha256:shaFile(p),quads:qs.length,triangles:nF,vertices:nV,bytes:fs.statSync(p).size};}
const meshes={};for(const [mat,qs] of [...quads.entries()].sort((a,b)=>a[0]-b[0]))meshes[mat]=writePly(mat,qs);

// Occupancy/material statistics and emissive centroids.
let min=[X,Y,Z],max=[-1,-1,-1],solid=0;const matAgg={};for(let z=0;z<Z;z++)for(let y=0;y<Y;y++)for(let x=0;x<X;x++){const id=sample(x,y,z);if(!id)continue;solid++;if(x<min[0])min[0]=x;if(y<min[1])min[1]=y;if(z<min[2])min[2]=z;if(x>max[0])max[0]=x;if(y>max[1])max[1]=y;if(z>max[2])max[2]=z;if(emissive(id)){let a=matAgg[id];if(!a)a=matAgg[id]={n:0,sx:0,sy:0,sz:0,min:[X,Y,Z],max:[-1,-1,-1]};a.n++;a.sx+=x+.5;a.sy+=y+.5;a.sz+=z+.5;for(let k=0;k<3;k++){const q=[x,y,z][k];if(q<a.min[k])a.min[k]=q;if(q>a.max[k])a.max[k]=q;}}}
function gridToWorld(g){return [g[0]*W.vm+shift[0],g[1]*W.vm+shift[1],g[2]*W.vm+shift[2]];} function worldToGrid(p){return [(p[0]-shift[0])/W.vm,p[1]/W.vm,(p[2]-shift[2])/W.vm];}
const bmin=gridToWorld(min),bmax=gridToWorld([max[0]+1,max[1]+1,max[2]+1]);
const emissiveCenters=Object.entries(matAgg).map(([id,a])=>({id:Number(id),world:gridToWorld([a.sx/a.n,a.sy/a.n,a.sz/a.n]),count:a.n,name:infos[id].name}));
function norm(v){const l=Math.hypot(...v);return l>0?v.map(x=>x/l):[0,0,0];} function dot(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2];} function sub(a,b){return a.map((x,i)=>x-b[i]);} function add(a,b){return a.map((x,i)=>x+b[i]);} function mul(a,s){return a.map(x=>x*s);} function dist(a,b){return Math.hypot(...sub(a,b));}
function trace(origin,dir,maxDist=28){dir=norm(dir);const g=worldToGrid(origin);let ix=Math.floor(g[0]),iy=Math.floor(g[1]),iz=Math.floor(g[2]);const step=[Math.sign(dir[0]),Math.sign(dir[1]),Math.sign(dir[2])];const td=[0,1,2].map(k=>Math.abs(dir[k])<1e-12?Infinity:W.vm/Math.abs(dir[k]));const tm=[0,1,2].map(k=>{if(Math.abs(dir[k])<1e-12)return Infinity;const cell=[ix,iy,iz][k],next=step[k]>0?cell+1:cell;const dg=next-g[k];return dg*W.vm/dir[k];});let t=0;for(let it=0;it<8192&&t<=maxDist;it++){if(ix<0||iy<0||iz<0||ix>=X||iy>=Y||iz>=Z)return {id:0,dist:t,miss:true};const id=sample(ix,iy,iz);if(id)return{id,dist:t,miss:false,cell:[ix,iy,iz]};let axis=0;if(tm[1]<tm[axis])axis=1;if(tm[2]<tm[axis])axis=2;t=tm[axis];tm[axis]+=td[axis];if(axis===0)ix+=step[0];else if(axis===1)iy+=step[1];else iz+=step[2];}return{id:0,dist:maxDist,miss:true};}
function dirYawPitch(yaw,pitch){const y=yaw*Math.PI/180,p=pitch*Math.PI/180,cp=Math.cos(p);return [Math.sin(y)*cp,Math.sin(p),Math.cos(y)*cp];}
function floorSupport(x,y,z,r){const pts=[[0,0],[r,0],[-r,0],[0,r],[0,-r],[r,r],[r,-r],[-r,r],[-r,-r]];let n=0;for(const [dx,dz] of pts)if(opaque(sample(x+dx,y,z+dz)))n++;return n/pts.length;}
function findWalkable(){const eyeH=1.65,bodyH=1.90,eyeV=eyeH/W.vm,clearV=Math.ceil(bodyH/W.vm),step=Math.max(4,Math.round(1.5/W.vm)),r=Math.max(1,Math.round(.25/W.vm));const C=[];for(let z=Math.floor(step/2);z<Z;z+=step)for(let x=Math.floor(step/2);x<X;x+=step){for(let y=0;y<Y-clearV-2;y++){if(!opaque(sample(x,y,z))||sample(x,y+1,z)!==0)continue;if(floorSupport(x,y,z,r)<.55)continue;let clear=true;for(let yy=y+1;yy<=y+clearV;yy++)if(sample(x,yy,z)!==0){clear=false;break;}if(!clear)continue;const eye=gridToWorld([x+.5,y+1+eyeV,z+.5]);C.push({x,y,z,eye});}}return C;}
function stdev(a){if(!a.length)return 0;const m=a.reduce((s,x)=>s+x,0)/a.length;return Math.sqrt(a.reduce((s,x)=>s+(x-m)*(x-m),0)/a.length);}
function evaluateView(c,yaw){const maxD=26,fan=[];for(const pitch of [-14,0,14])for(const yo of [-28,-14,0,14,28])fan.push(trace(c.eye,dirYawPitch(yaw+yo,pitch),maxD));const d=fan.map(h=>h.miss?maxD:h.dist),hit=fan.filter(h=>!h.miss),missFrac=(fan.length-hit.length)/fan.length,near=hit.filter(h=>h.dist<4.5).length/fan.length,far=fan.filter(h=>h.miss||h.dist>11).length/fan.length,matSet=new Set(hit.map(h=>h.id)),matDiv=Math.min(1,matSet.size/7),depthVar=Math.min(1,stdev(d)/9),emissiveHits=hit.filter(h=>emissive(h.id)),emFrac=emissiveHits.length/fan.length,special=hit.filter(h=>['water','glass','dielectric','conductor'].includes(infos[h.id]?.kind)).length/fan.length;let emLOS=0,nearestVisibleEmitter=Infinity;const fwd=dirYawPitch(yaw,0);for(const e of emissiveCenters){const v=sub(e.world,c.eye),dd=Math.hypot(...v);if(dd>34||dd<.75)continue;const a=dot(norm(v),fwd);if(a<Math.cos(42*Math.PI/180))continue;const h=trace(c.eye,v,dd+.3);if(h.id===e.id){nearestVisibleEmitter=Math.min(nearestVisibleEmitter,dd);const distanceQuality=Math.exp(-Math.abs(dd-6)/8);emLOS+=distanceQuality;}}
 const up=trace(c.eye,[0,1,0],18),covered=!up.miss;let enc=0;for(let k=0;k<8;k++){const h=trace(c.eye,dirYawPitch(k*45,0),8);if(!h.miss)enc++;}enc/=8;const center=trace(c.eye,fwd,maxD);let centerPenalty=!center.miss&&center.dist<1.4?2.5:0;if(!center.miss&&emissive(center.id)&&center.dist<2.2)centerPenalty+=10*(2.2-center.dist)/2.2;const foliageCenterPenalty=!center.miss&&/leaf|foliage/.test(infos[center.id]?.name||'')?2.0:0;const emitterFillPenalty=Math.max(0,emFrac-.35)*18;const emitterPresence=Math.min(1,emFrac/.12);const emitterQuality=2.2*emitterPresence+2.5*emLOS-emitterFillPenalty;const cross=near*far;
 return {yaw,covered,enclosure:enc,missFrac,nearFrac:near,farFrac:far,materialDiversity:matDiv,depthVariation:depthVar,emissiveVisible:emitterQuality,emissiveFraction:emFrac,nearestVisibleEmitter:Number.isFinite(nearestVisibleEmitter)?nearestVisibleEmitter:null,specialFraction:special,centerHit:center.miss?null:{id:center.id,dist:center.dist,name:infos[center.id]?.name},scores:{emissive:4.2*emitterQuality+1.2*matDiv+1.4*depthVar+2*cross+special-centerPenalty,threshold:(covered?1.7:.65)*(5*near*missFrac+3.5*cross)+1.7*depthVar+.8*matDiv+.5*special-centerPenalty,occluded:1.5*(covered?1:0)+2*enc+1.2*near+1.0*matDiv+1.3*depthVar+.5*(1-missFrac)-centerPenalty-foliageCenterPenalty,mixed:1.6*depthVar+1.2*matDiv+2*cross+.8*special+.9*Math.max(0,emitterQuality)+.5*enc-centerPenalty-.5*foliageCenterPenalty}};}
const walkable=findWalkable();let views=[];for(const c of walkable)for(let yaw=0;yaw<360;yaw+=30){const v=evaluateView(c,yaw);if(Object.values(v.scores).some(s=>s>0))views.push({...c,...v});}
function choose(category,chosen){const sorted=[...views].sort((a,b)=>b.scores[category]-a.scores[category]);for(const v of sorted){let ok=true;for(const q of chosen){if(dist(v.eye,q.eye)<4.0&&Math.abs((((v.yaw-q.yaw)+540)%360)-180)<75){ok=false;break;}}if(ok)return v;}return sorted[0];}
const hasEmissive=emissiveCenters.length>0;const cats=hasEmissive?['emissive','threshold','occluded']:['threshold','occluded','mixed'];const chosen=[];for(const cat of cats.slice(0,cameraCount)){const v=choose(cat,chosen);if(v){const fwd=dirYawPitch(v.yaw,0),focus=v.centerHit?clamp(v.centerHit.dist*.9,3.0,15):10;chosen.push({...v,name:`fps_${cat}`,category:cat,target:add(v.eye,mul(fwd,focus)),fov:70});}}
if(chosen.length<cameraCount){for(const cat of ['mixed','threshold','occluded','emissive']){if(chosen.length>=cameraCount)break;const v=choose(cat,chosen);if(v)chosen.push({...v,name:`fps_${cat}_${chosen.length}`,category:cat,target:add(v.eye,mul(dirYawPitch(v.yaw,0),v.centerHit?clamp(v.centerHit.dist*.9,3,15):10)),fov:70});}}
function fmt3(a){return a.map(v=>Number(v).toFixed(6)).join(' ');} function matDecl(info){const key=`mat_${info.id}`;if(info.kind==='conductor')return `MakeNamedMaterial "${key}" "string type" "conductor" "rgb reflectance" [${fmt3(info.base)}] "float roughness" [${info.alpha}] "bool remaproughness" [false]\n`;if(['water','glass','dielectric'].includes(info.kind))return `MakeNamedMaterial "${key}" "string type" "dielectric" "float eta" [${info.eta}] "float roughness" [${info.alpha}] "bool remaproughness" [false]\n`;return `MakeNamedMaterial "${key}" "string type" "diffuse" "rgb reflectance" [${fmt3(info.base)}]\n`;}
const matIds=[...quads.keys()].sort((a,b)=>a-b),anyWater=matIds.some(id=>infos[id].kind==='water');
function worldBody(includeMedium){let s='WorldBegin\nLightSource "infinite" "rgb L" [0.10 0.14 0.22]\nLightSource "distant" "rgb L" [3.2 2.85 2.35] "point3 from" [-30 45 -50] "point3 to" [0 0 0]\n';for(const id of matIds)s+=matDecl(infos[id]);for(const id of matIds){const info=infos[id],mesh=meshes[id];s+='AttributeBegin\n';s+=`NamedMaterial "mat_${id}"\n`;if(includeMedium&&info.kind==='water')s+='MediumInterface "water_medium" ""\n';if(info.emission.some(v=>v>0))s+=`AreaLightSource "diffuse" "rgb L" [${fmt3(info.emission)}]\n`;s+=`Shape "plymesh" "string filename" ["${mesh.name}"]\nAttributeEnd\n`;}return s;}
function header(cam,film,filename,spp,integrator){let s=`LookAt ${fmt3(cam.eye)}\n       ${fmt3(cam.target)}\n       0 1 0\nCamera "perspective" "float fov" [${cam.fov}]\n`;if(film==='gbuffer')s+=`Film "gbuffer" "integer xresolution" [${xres}] "integer yresolution" [${yres}] "string filename" ["${filename}"] "bool savefp16" [false] "string coordinatesystem" ["world"]\n`;else s+=`Film "rgb" "integer xresolution" [${xres}] "integer yresolution" [${yres}] "string filename" ["${filename}"] "bool savefp16" [false]\n`;s+=`Sampler "halton" "integer pixelsamples" [${spp}] "integer seed" [73]\n${integrator}\n`;return s;}
const base=path.basename(levelFile,'.js');for(const cam of chosen){const beautyName=`${base}_${cam.name}_beauty_${beautySpp}spp.exr`,totalName=`${base}_${cam.name}_irr_total_${irrSpp}spp.exr`,directName=`${base}_${cam.name}_irr_direct_${irrSpp}spp.exr`;let pre=header(cam,'rgb',beautyName,beautySpp,'Integrator "volpath" "integer maxdepth" [10]');if(anyWater)pre+=`MakeNamedMedium "water_medium" "string type" "homogeneous" "rgb sigma_a" [0.18 0.07 0.025] "rgb sigma_s" [0.008 0.012 0.016]\n`;let p=path.join(outDir,`${base}_${cam.name}_beauty.pbrt`);fs.writeFileSync(p,pre+worldBody(true));cam.beautyScene=path.basename(p);cam.beautySceneSha256=shaFile(p);p=path.join(outDir,`${base}_${cam.name}_irr_total.pbrt`);fs.writeFileSync(p,header(cam,'gbuffer',totalName,irrSpp,'Integrator "irradiance" "integer maxdepth" [8] "string component" ["total"]')+worldBody(false));cam.totalScene=path.basename(p);cam.totalSceneSha256=shaFile(p);p=path.join(outDir,`${base}_${cam.name}_irr_direct.pbrt`);fs.writeFileSync(p,header(cam,'rgb',directName,irrSpp,'Integrator "irradiance" "integer maxdepth" [8] "string component" ["direct"]')+worldBody(false));cam.directScene=path.basename(p);cam.directSceneSha256=shaFile(p);}
const manifest={schema:2,source:path.basename(levelFile),sourceSha256:shaFile(path.resolve(levelFile)),fingerprint64:W.level.fingerprint64||null,dims:W.dims,voxelMeters:W.vm,solidVoxels:solid,boundsMeters:{min:bmin,max:bmax},meshStats:stats,meshes,materials:Object.fromEntries(matIds.map(id=>[id,infos[id]])),lighting:{environmentRGB:[.10,.14,.22],distantRGB:[3.2,2.85,2.35],distantFrom:[-30,45,-50],emissiveMaterials:emissiveCenters},irradianceScope:{definition:'camera-visible geometric-side hemispherical irradiance',participatingMedia:false,note:'water/glass remain dielectric interfaces; homogeneous medium attenuation is excluded until irradiance integrator gains volpath-equivalent medium random walks'},cameraSelection:{eyeHeightMeters:1.65,candidateStepMeters:Math.max(4,Math.round(1.5/W.vm))*W.vm,walkableCandidates:walkable.length,evaluatedViews:views.length,categories:cats},cameras:chosen.map(c=>({name:c.name,category:c.category,eye:c.eye,target:c.target,fov:c.fov,yaw:c.yaw,covered:c.covered,enclosure:c.enclosure,missFrac:c.missFrac,nearFrac:c.nearFrac,farFrac:c.farFrac,materialDiversity:c.materialDiversity,depthVariation:c.depthVariation,emissiveVisible:c.emissiveVisible,emissiveFraction:c.emissiveFraction,nearestVisibleEmitter:c.nearestVisibleEmitter,specialFraction:c.specialFraction,centerHit:c.centerHit,scores:c.scores,beautyScene:c.beautyScene,beautySceneSha256:c.beautySceneSha256,totalScene:c.totalScene,totalSceneSha256:c.totalSceneSha256,directScene:c.directScene,directSceneSha256:c.directSceneSha256})),adapterSha256:shaFile(__filename)};fs.writeFileSync(path.join(outDir,'manifest.json'),JSON.stringify(manifest,null,2));console.log(JSON.stringify({source:manifest.source,dims:W.dims,vm:W.vm,solid,quads:stats.greedyQuads,triangles:stats.greedyQuads*2,materials:quads.size,ambiguous:stats.ambiguousTransmissive,walkable:walkable.length,emissives:emissiveCenters.length,cameras:manifest.cameras},null,2));
